// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB54ybTlb8cqaHvkNDsSIzRcZIAu32h5kU',
    appId: '1:269950662952:web:836425d93a0c71a0c2781d',
    messagingSenderId: '269950662952',
    projectId: 'bitirmecalismasi-399df',
    authDomain: 'bitirmecalismasi-399df.firebaseapp.com',
    storageBucket: 'bitirmecalismasi-399df.firebasestorage.app',
    measurementId: 'G-5S03LJLDYH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhHbwNtNxz1IdqvwPYXYz6XcY-eTMuiZ0',
    appId: '1:269950662952:android:bb46df6e9f84e9edc2781d',
    messagingSenderId: '269950662952',
    projectId: 'bitirmecalismasi-399df',
    storageBucket: 'bitirmecalismasi-399df.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6Q0xDrBELHlR7o0D-UbH_42Kyl8Cn2gM',
    appId: '1:269950662952:ios:bcc2c6400b19add5c2781d',
    messagingSenderId: '269950662952',
    projectId: 'bitirmecalismasi-399df',
    storageBucket: 'bitirmecalismasi-399df.firebasestorage.app',
    iosBundleId: 'com.example.proje',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6Q0xDrBELHlR7o0D-UbH_42Kyl8Cn2gM',
    appId: '1:269950662952:ios:bcc2c6400b19add5c2781d',
    messagingSenderId: '269950662952',
    projectId: 'bitirmecalismasi-399df',
    storageBucket: 'bitirmecalismasi-399df.firebasestorage.app',
    iosBundleId: 'com.example.proje',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB54ybTlb8cqaHvkNDsSIzRcZIAu32h5kU',
    appId: '1:269950662952:web:22fe00b673c4896cc2781d',
    messagingSenderId: '269950662952',
    projectId: 'bitirmecalismasi-399df',
    authDomain: 'bitirmecalismasi-399df.firebaseapp.com',
    storageBucket: 'bitirmecalismasi-399df.firebasestorage.app',
    measurementId: 'G-MVJ9Z64PPP',
  );
}
